# Generated by Django 5.2.4 on 2025-07-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Опыт работы', 'verbose_name_plural': 'Опыт работы'},
        ),
        migrations.AlterModelOptions(
            name='experiencetranslation',
            options={'verbose_name': 'Перевод опыта', 'verbose_name_plural': 'Переводы опыта'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterModelOptions(
            name='profiletranslation',
            options={'verbose_name': 'Перевод профиля', 'verbose_name_plural': 'Переводы профилей'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['technology__category', 'technology__name'], 'verbose_name': 'Навык', 'verbose_name_plural': 'Навыки'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Технология', 'verbose_name_plural': 'Технологии'},
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('profile', 'technology')},
        ),
    ]
