# Generated by Django 5.2.4 on 2025-07-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('date_issued', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='certificates/')),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
